[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Quan Le <leminhquan310@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
qdrant-client = "^1.10.1"
openai = "^1.37.1"
fastapi = "^0.111.1"
starlette = "0.37.2"
llama-index = "^0.10.58"
llama-index-llms-huggingface-api = "^0.1.0"
llama-index-llms-huggingface = "^0.2.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
