[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Quan Le <leminhquan310@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
qdrant-client = "^1.10.1"
openai = "^1.37.1"
fastapi = "^0.111.1"
starlette = "0.37.2"
langchain = "^0.2.11"
huggingface-hub = "^0.24.2"
langchain-huggingface = "^0.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
